project:
  type: website
  output-dir: docs

website:
  title: "Mid Project"
  navbar:
    left:
      - href: Project.qmd
        text: Home
      - href: about.qmd
        text: "Code Overview"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

